# This is a basic workflow to help you get started with Actions
# https://stackoverflow.com/questions/4297014/what-are-the-differences-between-pmd-and-findbugs

name: Checkstyle

# Controls when the workflow will run
on:
  # Triggers the workflow on push for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # static analysis reporting
      - name: Checkstyle Report
        run: mvn -B verify checkstyle:checkstyle
      - uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: "**/checkstyle-result.xml"
      - name: Checkstyle Check
        run: mvn -B verify checkstyle:check